FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish Fg.Homewizard.DataCollector.csproj -c Release -o Fg.Homewizard.DataCollector/out

FROM mcr.microsoft.com/dotnet/runtime:8.0-bookworm-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/Fg.Homewizard.DataCollector/out ./
COPY qemu-arm-static /usr/bin/qemu-arm-static

ENTRYPOINT ["dotnet", "Fg.Homewizard.DataCollector.dll"]